import { Investigation } from "@/types";

export const investigations: Investigation[] = [
  {
    id: "new-cohort-quality",
    slug: "new-cohort-quality",
    title: "New paid cohorts show weaker repeat economics",
    question: "Why are new paid cohorts repeating less?",
    trigger: "30-day repeat -7.4 pp",
    category: "Acquisition",
    additionalCategories: ["Retention", "Pricing", "Promotions", "Channel"],
    economicImpact: 1_180_000,
    impactHorizon: "180 days",
    hilbertConfidence: 88,
    operatorStatus: "testing",
    operatorConfidence: "High",
    customerStatus: "not_shared",
    hilbertAnswer:
      "New paid cohorts are lower quality primarily because acquisition shifted toward broad paid-social audiences with weaker repeat propensity. Deeper first-order discounts appear to amplify the effect.",
    hilbertPrimaryDriver: "Channel mix",
    hilbertSecondaryDriver: "Promotion depth",
    hilbertLeadingIndicator: "14-day engagement / second-purchase intent",
    operatorNote:
      "Channel and promotional mix changed simultaneously. Need to separate the effects before presenting this as causal.",
    operatorConclusion:
      "The newest paid cohorts are genuinely weaker, and the deterioration is concentrated in broad paid-social acquisition. Higher prices explain most of the apparent AOV strength but not the decline in repeat behavior. Deeper first-order promotions are associated with additional weakness after controlling for channel and basket characteristics. Fulfillment and data quality do not appear to be primary causes.",
    hypotheses: [
      {
        id: "h1",
        label: "H1 — Lower-intent acquisition mix",
        statement: "New paid customers are genuinely lower intent.",
        status: "supported",
        evidenceFor: [
          "Broad social share rose 14 pp",
          "These users show lower day-14 engagement",
          "Within comparable discount depth, repeat remains weaker",
        ],
        evidenceAgainst: [],
        confidence: 82,
      },
      {
        id: "h2",
        label: "H2 — Promotion artifact",
        statement: "Aggressive first-order offers pulled demand forward or acquired promotion-dependent customers.",
        status: "partially_supported",
        evidenceFor: [
          "First-order discount rose from 13.2% to 21.7%",
          "Deep-discount cohorts repeat less",
          "Channel-adjusted effect remains meaningful",
        ],
        evidenceAgainst: [],
        confidence: 68,
      },
      {
        id: "h3",
        label: "H3 — Pricing artifact",
        statement: "AOV rose because prices rose, making revenue look healthier while unit demand weakened.",
        status: "partially_supported",
        evidenceFor: ["Effective prices increased 7.6%", "Unit count / basket fell"],
        evidenceAgainst: ["Repeat deterioration persists after price-normalized analysis"],
        confidence: 55,
      },
      {
        id: "h4",
        label: "H4 — Fulfillment deterioration",
        statement: "Delivery availability / fulfillment quality reduced repeat behavior.",
        status: "ruled_out",
        evidenceFor: [],
        evidenceAgainst: [
          "On-time delivery stable",
          "Cancellation rate stable",
          "Affected and unaffected cohorts show similar service levels",
        ],
        confidence: 12,
      },
      {
        id: "h5",
        label: "H5 — Seasonal change",
        statement: "The decline reflects normal seasonal variation.",
        status: "ruled_out",
        evidenceFor: [],
        evidenceAgainst: ["Prior-year cohorts do not show similar deterioration", "Divergence exceeds historical seasonal band"],
        confidence: 8,
      },
      {
        id: "h6",
        label: "H6 — Data / identity issue",
        statement: "Tracking or identity changes made newer cohorts look worse than they are.",
        status: "ruled_out",
        evidenceFor: [],
        evidenceAgainst: ["Match rate stable", "Event completeness 98.8%", "No schema change coincides with divergence"],
        confidence: 6,
      },
    ],
    evidence: [
      {
        id: "e1",
        title: "30-day second-purchase rate by acquisition cohort",
        type: "descriptive",
        metric: "repeat_30d",
        result: "Paid-social 30-day repeat fell from 36.2% (Jan) to 25.4% (Jul); other channels moved -1.2 pp.",
        source: "orders + acquisition",
      },
      {
        id: "e2",
        title: "Price-normalized units per customer",
        type: "descriptive",
        metric: "units_per_customer_60d",
        result: "60-day units / customer declined 10.7% even as nominal revenue rose.",
        source: "order_items · price-normalized",
      },
      {
        id: "e3",
        title: "Matched-cohort promotion test",
        type: "matched",
        metric: "repeat_90d",
        result: "-5.1 pp repeat gap after matching on channel, category, geography, basket, and acquisition week.",
        source: "promotions + cohort features",
        caveat: "Observational. Promotion depth is correlated with channel and campaign targeting.",
      },
      {
        id: "e4",
        title: "Fulfillment service levels",
        type: "descriptive",
        result: "On-time delivery and cancellation rate stable across affected and unaffected cohorts.",
        source: "fulfillment_events",
      },
    ],
    validationChecks: [
      { id: "v1", label: "Compare against prior-year seasonality", completed: true, result: "Divergence exceeds seasonal band" },
      { id: "v2", label: "Normalize for price changes", completed: true, result: "Repeat decline persists after normalization" },
      { id: "v3", label: "Check fulfillment metrics", completed: true, result: "Stable, ruled out" },
      { id: "v4", label: "Check identity / tracking quality", completed: true, result: "Match rate stable" },
      { id: "v5", label: "Segment by acquisition channel", completed: true, result: "Effect concentrated in Meta Broad" },
      { id: "v6", label: "Control for first-order promotion depth", completed: true, result: "Effect persists after controls" },
      { id: "v7", label: "Inspect category mix", completed: false },
      { id: "v8", label: "Validate campaign-level spend changes with customer", completed: false },
      { id: "v9", label: "Confirm promotion policy change date", completed: true, result: "Policy broadened May 3" },
    ],
    recommendedActions: [
      {
        id: "a1",
        title: "Reallocate low-quality paid spend",
        description: "Move 12% of Meta Broad spend into Lookalike + high-pLTV audiences.",
        expectedImpact: 610_000,
        impactHorizon: "180 days",
        timeToSignal: "30-45 days",
        risk: "medium",
        measurementPlan: ["30-day repeat by channel", "Blended CAC"],
        recommended: true,
      },
      {
        id: "a2",
        title: "Replace blanket first-order discounting",
        description: "Keep deeper offers only for high predicted-repeat-propensity / price-sensitive segments.",
        expectedImpact: 360_000,
        impactHorizon: "180 days",
        timeToSignal: "45-60 days",
        risk: "medium",
        measurementPlan: ["Repeat by discount depth", "First-order margin"],
      },
      {
        id: "a3",
        title: "Build second-purchase intervention",
        description: "Trigger 7-14 days after first order for high-value non-repeaters.",
        expectedImpact: 210_000,
        impactHorizon: "180 days",
        timeToSignal: "21-30 days",
        risk: "low",
        measurementPlan: ["Second-purchase conversion", "Intervention reach"],
      },
    ],
    driverDecomposition: [
      { label: "Acquisition mix", pct: 61 },
      { label: "Promotion depth", pct: 17 },
      { label: "Category / basket mix", pct: 9 },
      { label: "Geography", pct: 4 },
      { label: "Unexplained", pct: 9 },
    ],
    unknowns: [
      {
        id: "u1",
        statement: "Campaign creative is not represented in current model",
        potentialImpact: "Creative fatigue could explain part of the audience-quality decline independent of targeting.",
        changesRecommendation: false,
        followUpRequired: "Request creative-level metadata from Meta export.",
      },
      {
        id: "u2",
        statement: "Matched promotion analysis remains observational",
        potentialImpact: "True incrementality could be lower or higher than the matched estimate.",
        changesRecommendation: false,
        followUpRequired: "Consider a holdout experiment on discount depth.",
      },
      {
        id: "u3",
        statement: "Competitor pricing is not included",
        potentialImpact: "Some of the repeat decline could reflect competitive response, not acquisition quality.",
        changesRecommendation: false,
        followUpRequired: "None planned — no reliable competitor pricing feed available.",
      },
      {
        id: "u4",
        statement: "Household identity may undercount cross-device behavior by ~1.2%",
        potentialImpact: "Slight understatement of true repeat rate across all cohorts equally.",
        changesRecommendation: false,
        followUpRequired: "Monitor with identity-resolution vendor upgrade.",
      },
    ],
    updatedAt: "2026-08-14T09:20:00Z",
  },
  {
    id: "winback-dormant-households",
    slug: "winback-dormant-households",
    title: "Dormant high-value households are reactivating too late",
    question: "Can we recover dormant high-value households before they fully churn?",
    trigger: "84K households 45-90 days beyond expected cadence",
    category: "Retention",
    economicImpact: 420_000,
    impactHorizon: "reactivation window",
    hilbertConfidence: 74,
    operatorStatus: "validated",
    operatorConfidence: "Medium",
    customerStatus: "shared",
    hilbertAnswer:
      "84K historically high-basket-value households have gone 45-90 days beyond their expected purchase cadence. Reactivation likelihood drops sharply after 120 days.",
    hilbertPrimaryDriver: "Cadence-based decay",
    hypotheses: [
      {
        id: "h1",
        label: "H1 — Natural decay curve",
        statement: "Reactivation odds fall predictably with days-since-expected-cadence.",
        status: "supported",
        evidenceFor: ["Historical reactivation curve shows steep drop after 120 days"],
        evidenceAgainst: [],
        confidence: 79,
      },
    ],
    evidence: [
      {
        id: "e1",
        title: "Household reactivation curve",
        type: "descriptive",
        result: "Reactivation probability falls from 34% (45-90d) to 9% (120d+).",
        source: "orders + loyalty",
      },
    ],
    validationChecks: [
      { id: "v1", label: "Confirm eligible cohort with SQL Lab", completed: true, result: "84,318 eligible" },
      { id: "v2", label: "Check for active service issues", completed: true, result: "No related complaints" },
    ],
    recommendedActions: [
      {
        id: "a1",
        title: "Launch personalized win-back before 120-day decay",
        description: "Target eligible households with a tailored offer before the reactivation curve flattens.",
        expectedImpact: 420_000,
        impactHorizon: "90 days",
        timeToSignal: "30 days",
        risk: "low",
        measurementPlan: ["Reactivation rate", "Recovered contribution"],
        recommended: true,
      },
    ],
    unknowns: [],
    updatedAt: "2026-08-12T14:00:00Z",
  },
  {
    id: "loyalty-frequency",
    slug: "loyalty-frequency",
    title: "Loyalty membership frequency advantage",
    question: "Which loyalty behaviors truly compound?",
    trigger: "Member monthly frequency 3.2 vs. non-member 2.1",
    category: "Loyalty",
    economicImpact: 0,
    impactHorizon: "ongoing",
    hilbertConfidence: 81,
    operatorStatus: "ready_for_customer",
    operatorConfidence: "High",
    customerStatus: "draft",
    hilbertAnswer:
      "Members are compounding purchase frequency faster than non-members, with a 14.6 pp retention advantage.",
    hilbertPrimaryDriver: "Membership behavior",
    hypotheses: [
      {
        id: "h1",
        label: "H1 — Incremental membership value",
        statement: "Membership causes higher frequency, not just selection of already-frequent shoppers.",
        status: "partially_supported",
        evidenceFor: ["Matched comparison still shows a 24% LTV advantage"],
        evidenceAgainst: ["Raw advantage (61%) is much larger than matched advantage (24%), indicating selection"],
        confidence: 71,
      },
    ],
    evidence: [
      {
        id: "e1",
        title: "Member vs. matched non-member economics",
        type: "matched",
        result: "Matched comparison shows +24% p180 LTV advantage for members vs. +61% raw.",
        source: "loyalty + orders · matched observational comparison",
      },
    ],
    validationChecks: [
      { id: "v1", label: "Matched-strata comparison by acquisition month, geography, pre-membership frequency", completed: true },
    ],
    recommendedActions: [
      {
        id: "a1",
        title: "Target high-frequency non-members for membership conversion",
        description: "Prioritize non-members whose behavior already resembles member cohorts.",
        expectedImpact: 0,
        impactHorizon: "180 days",
        timeToSignal: "60 days",
        risk: "low",
        measurementPlan: ["Membership conversion rate", "Post-conversion frequency change"],
        recommended: true,
      },
    ],
    unknowns: [],
    updatedAt: "2026-08-10T11:30:00Z",
  },
  {
    id: "prepared-foods-frequency",
    slug: "prepared-foods-frequency",
    title: "Prepared-food assortment opportunity",
    question: "Which assortment changes increase repeat visits?",
    trigger: "Attach-rate increase +18%, frequency lift +9.4%",
    category: "Assortment",
    economicImpact: 0,
    impactHorizon: "ongoing",
    hilbertConfidence: 63,
    operatorStatus: "waiting_for_data",
    operatorConfidence: "Medium",
    customerStatus: "not_shared",
    hilbertAnswer: "Prepared foods increase basket frequency among high-value urban customers.",
    hilbertPrimaryDriver: "Category adoption",
    operatorNote: "Possible selection effect: high-frequency households may self-select into prepared foods.",
    hypotheses: [
      {
        id: "h1",
        label: "H1 — Causal frequency lift",
        statement: "Prepared-food exposure causes higher visit frequency.",
        status: "inconclusive",
        evidenceFor: ["Exposed customers order 2.04x/period vs 1.55x unexposed"],
        evidenceAgainst: ["No geo-level exposure experiment yet run"],
        confidence: 48,
      },
    ],
    evidence: [
      {
        id: "e1",
        title: "Prepared-food exposure vs. order frequency",
        type: "descriptive",
        result: "Exposed customers show 32% higher orders/customer than unexposed.",
        source: "order_items · category = Prepared Foods",
        caveat: "Association may reflect customer self-selection.",
      },
    ],
    validationChecks: [{ id: "v1", label: "Run geo/store-level exposure experiment", completed: false }],
    recommendedActions: [
      {
        id: "a1",
        title: "Test increased prepared-food visibility in matched delivery zones",
        description: "Run a store/zone-level exposure experiment to separate causal lift from selection.",
        expectedImpact: 0,
        impactHorizon: "90 days",
        timeToSignal: "60-90 days",
        risk: "low",
        measurementPlan: ["Visit frequency", "Basket", "Contribution margin"],
        recommended: true,
      },
    ],
    unknowns: [],
    updatedAt: "2026-08-09T16:45:00Z",
  },
  {
    id: "branded-search-efficiency",
    slug: "branded-search-efficiency",
    title: "Branded search efficiency decline",
    question: "Where should paid budget move?",
    trigger: "Branded search CAC +16% with flat pLTV",
    category: "Channel",
    additionalCategories: ["Pricing"],
    economicImpact: 96_000,
    impactHorizon: "monthly",
    hilbertConfidence: 69,
    operatorStatus: "new",
    customerStatus: "not_shared",
    hilbertAnswer: "Branded search CAC rose 16% without a corresponding increase in incremental LTV.",
    hilbertPrimaryDriver: "Auction competition",
    hypotheses: [
      {
        id: "h1",
        label: "H1 — Rising auction competition",
        statement: "CPCs rose due to competitive bidding, not demand quality change.",
        status: "untested",
        evidenceFor: [],
        evidenceAgainst: [],
        confidence: 40,
      },
    ],
    evidence: [
      {
        id: "e1",
        title: "Branded search CAC trend",
        type: "descriptive",
        result: "CAC +16% month-over-month; pLTV flat.",
        source: "acquisition + orders",
      },
    ],
    validationChecks: [{ id: "v1", label: "Check auction overlap / impression share", completed: false }],
    recommendedActions: [
      {
        id: "a1",
        title: "Cap branded search bids at historical CAC target",
        description: "Reduce estimated monthly overspend while investigating auction dynamics.",
        expectedImpact: 96_000,
        impactHorizon: "monthly",
        timeToSignal: "14 days",
        risk: "low",
        measurementPlan: ["Blended CAC", "Impression share"],
      },
    ],
    unknowns: [],
    updatedAt: "2026-08-08T13:10:00Z",
  },
  {
    id: "promo-leakage",
    slug: "promo-leakage",
    title: "Promotion leakage among one-time buyers",
    question: "Are promotions creating incremental behavior?",
    trigger: "17,842 first-time purchasers, no repeat after 90+ days",
    category: "Promotions",
    economicImpact: 330_000,
    impactHorizon: "annual",
    hilbertConfidence: 79,
    operatorStatus: "validated",
    customerStatus: "not_shared",
    hilbertAnswer: "Blanket discounting is leaking margin into one-time buyers who never repeat.",
    hilbertPrimaryDriver: "Promotion targeting breadth",
    hypotheses: [
      {
        id: "h1",
        label: "H1 — Broad targeting acquires low-intent buyers",
        statement: "Untargeted deep discounts disproportionately acquire one-time, promotion-only buyers.",
        status: "supported",
        evidenceFor: ["17,842 first-time purchasers with no repeat after 90+ days", "$612K promotional cost tied to this group"],
        evidenceAgainst: [],
        confidence: 76,
      },
    ],
    evidence: [
      {
        id: "e1",
        title: "One-time buyer promotion cost",
        type: "descriptive",
        result: "$612K promotional cost attributable to non-repeating first-time buyers.",
        source: "promotions + orders",
      },
    ],
    validationChecks: [{ id: "v1", label: "Segment leakage by offer type", completed: true, result: "Concentrated in 20% first-order offer" }],
    recommendedActions: [
      {
        id: "a1",
        title: "Restrict deep first-order offers to high predicted-repeat segments",
        description: "Reduce blanket eligibility for the 20% first-order discount.",
        expectedImpact: 330_000,
        impactHorizon: "annual",
        timeToSignal: "60 days",
        risk: "medium",
        measurementPlan: ["Promo leakage rate", "First-order conversion"],
        recommended: true,
      },
    ],
    unknowns: [],
    updatedAt: "2026-08-07T10:05:00Z",
  },
];

export function getInvestigation(slug: string): Investigation | undefined {
  return investigations.find((i) => i.slug === slug);
}
