import { ProductFeedback } from "@/types";

export const productFeedback: ProductFeedback[] = [
  {
    id: "pf-1",
    customer: "Northstar Market",
    investigationId: "new-cohort-quality",
    title: "Promotion and channel mix confounding",
    hilbertOutput: "61% of retention decline attributed to channel mix",
    operatorFinding:
      "Promotion depth changed simultaneously; attribution is overstated without controlling for offer depth.",
    businessConsequence: "Overstates channel mix as the primary lever, understating the promotion-policy lever.",
    type: "reasoning",
    severity: "high",
    reproducible: true,
    reproSteps: "Open New Cohort Quality investigation → Section H (driver decomposition) → compare to matched-cohort test result in Section F.",
    relevantQuery: "q-promo-depth",
    recommendedFix: "Include promo depth in root-cause decomposition when acquisition and offer policies move together.",
    affectedCustomers: "Any customer running simultaneous channel and promotion changes",
    urgency: "high",
    status: "accepted",
    createdAt: "2026-08-11T10:00:00Z",
  },
  {
    id: "pf-2",
    customer: "Northstar Market",
    investigationId: "new-cohort-quality",
    title: "Price-driven AOV misread as basket improvement",
    hilbertOutput: "Basket quality improved 8.9%",
    operatorFinding: "Effective price rose 7.6%; units per basket declined.",
    businessConsequence: "Could lead a customer to celebrate a metric that masks weakening unit demand.",
    type: "metric_semantics",
    severity: "high",
    reproducible: true,
    reproSteps: "Open New Cohort Quality investigation → Section E (price normalization).",
    relevantQuery: "q-price-normalized",
    recommendedFix: "Always decompose AOV into price × units where item-level price data exists.",
    urgency: "high",
    status: "shipped",
    createdAt: "2026-08-09T15:30:00Z",
  },
  {
    id: "pf-3",
    customer: "Northstar Market",
    investigationId: "prepared-foods-frequency",
    title: "Prepared-food frequency opportunity may be selection bias",
    hilbertOutput: "Prepared foods increase basket frequency among high-value urban customers",
    operatorFinding: "High-frequency households may self-select into prepared foods; no exposure experiment run yet.",
    type: "causal_reasoning",
    severity: "medium",
    reproducible: true,
    recommendedFix: "Flag category-adoption findings as associative unless a geo/store exposure test exists.",
    status: "open",
    createdAt: "2026-08-09T09:00:00Z",
  },
  {
    id: "pf-4",
    customer: "Northstar Market",
    investigationId: "loyalty-frequency",
    title: "Loyalty renewal interpretation",
    hilbertOutput: "Member retention advantage +14.6 pp treated as fully incremental",
    operatorFinding: "Raw member advantage is inflated by selection; matched comparison shows roughly 40% of the raw effect.",
    type: "segment_definition",
    severity: "medium",
    reproducible: true,
    recommendedFix: "Surface matched vs. raw comparison by default for any member/non-member segment split.",
    status: "triaged",
    createdAt: "2026-08-06T12:15:00Z",
  },
  {
    id: "pf-5",
    customer: "Northstar Market",
    title: "Household identity edge case",
    hilbertOutput: "Household-level cross-device stitching assumed complete",
    operatorFinding: "~1.2% of sessions cannot be confidently linked to a household, understating true repeat rate slightly.",
    type: "data_quality",
    severity: "low",
    reproducible: false,
    recommendedFix: "Surface identity-match confidence alongside any household-level metric.",
    status: "open",
    createdAt: "2026-08-04T08:40:00Z",
  },
  {
    id: "pf-6",
    customer: "Northstar Market",
    title: "Category taxonomy change not flagged in trend charts",
    hilbertOutput: "July category attach rates shown continuous with June",
    operatorFinding: "Two categories changed taxonomy in July; the discontinuity should be annotated on trend charts.",
    type: "data_quality",
    severity: "low",
    reproducible: true,
    recommendedFix: "Annotate trend charts at known taxonomy-change dates.",
    status: "open",
    createdAt: "2026-08-02T14:20:00Z",
  },
];
